# Generated by Django 5.0.6 on 2024-08-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='companies/images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='employee_type',
            field=models.CharField(default='Full Time', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='offer_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(default='devoloper', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(default='many'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default='big'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills_experience',
            field=models.TextField(default='2 years'),
            preserve_default=False,
        ),
    ]
