# Generated by Django 5.0.6 on 2024-08-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_image_job_employee_type_job_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
