# Generated by Django 5.0.6 on 2024-08-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/images/'),
        ),
    ]
