# Generated by Django 5.0.6 on 2024-08-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0002_alter_jobseekerprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='first_name',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='last_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
