# Generated by Django 5.0.6 on 2024-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0003_jobseekerprofile_address_jobseekerprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='about',
            field=models.CharField(default='this is about job seekers', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education',
            field=models.CharField(default='International University education ', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experiences',
            field=models.CharField(default='Creative Agency experience', max_length=600),
            preserve_default=False,
        ),
    ]
