# Generated by Django 5.0.6 on 2024-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_jobseekerprofile_about_jobseekerprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='job_seekers/resumes/'),
        ),
    ]
